FROM --platform=$BUILDPLATFORM golang:1.26 AS build
ARG TARGETARCH
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN GOOS=linux GOARCH=$TARGETARCH CGO_ENABLED=0 go build -tags lambda.norpc -trimpath -ldflags="-s -w" -o /out/deploypulse ./cmd/deploypulse

FROM alpine:3.21 AS api
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:1.1.0 /lambda-adapter /opt/extensions/lambda-adapter
COPY --from=build /out/deploypulse /deploypulse
ENV AWS_LWA_READINESS_CHECK_PATH=/healthz
ENTRYPOINT ["/deploypulse", "api"]

FROM public.ecr.aws/lambda/provided:al2023 AS worker
COPY --from=build /out/deploypulse /deploypulse
ENTRYPOINT ["/deploypulse", "lambda-worker"]
